// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFSKpQAf_O-9zlCgX4EvDnlom0VCFC8Y',
    appId: '1:23321612099:web:e396d3c881e49b583c29f6',
    messagingSenderId: '23321612099',
    projectId: 'mo-tracker',
    authDomain: 'mo-tracker.firebaseapp.com',
    databaseURL: 'https://mo-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'mo-tracker.appspot.com',
    measurementId: 'G-FH4TEJB3L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdF6JNzN_2cot-H5qeThalFh5L_x3SF3Y',
    appId: '1:23321612099:android:4243ae77adf20cb43c29f6',
    messagingSenderId: '23321612099',
    projectId: 'mo-tracker',
    databaseURL: 'https://mo-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'mo-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPnua9aLig9Fu8PCi-jTehbXlUP2uo9bk',
    appId: '1:23321612099:ios:26acbe56709efbc33c29f6',
    messagingSenderId: '23321612099',
    projectId: 'mo-tracker',
    databaseURL: 'https://mo-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'mo-tracker.appspot.com',
    androidClientId: '23321612099-a1bo0lr375ongjt15upk3nl0bn36tgif.apps.googleusercontent.com',
    iosClientId: '23321612099-bnqgj6trnk9nh4k7sn9ef996ap9glsno.apps.googleusercontent.com',
    iosBundleId: 'com.example.moTimeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPnua9aLig9Fu8PCi-jTehbXlUP2uo9bk',
    appId: '1:23321612099:ios:26acbe56709efbc33c29f6',
    messagingSenderId: '23321612099',
    projectId: 'mo-tracker',
    databaseURL: 'https://mo-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'mo-tracker.appspot.com',
    androidClientId: '23321612099-a1bo0lr375ongjt15upk3nl0bn36tgif.apps.googleusercontent.com',
    iosClientId: '23321612099-bnqgj6trnk9nh4k7sn9ef996ap9glsno.apps.googleusercontent.com',
    iosBundleId: 'com.example.moTimeTracker',
  );
}
